export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GOOGLE_SIG_IN_START: "GOOGLE_SIG_IN_START",
  EMAIL_SIG_IN_START: "EMAIL_SIG_IN_START",
  SIG_IN_SUCCESS: "SIG_IN_SUCCESS",
  SIG_IN_FAILURE: "SIG_IN_FAILURE",
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  SIG_OUT_START: "SIG_OUT_START",
  SIG_OUT_SUCCESS: "SIG_OUT_SUCCESS",
  SIG_OUT_FAILURE: "SIG_OUT_FAILURE",
  SIG_UP_START: "SIG_UP_START",
  SIG_UP_SUCCESS: "SIG_UP_SUCCESS",
  SIG_UP_FAILURE: "SIG_UP_FAILURE",
};
