FROM docker/dev-environments-javascript:stable-1

RUN apt-get update \
    && curl -fsSL "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" -o /bin/pnpm; chmod +x /bin/pnpm;
